### ISSUE TITLE
move site to pages for 2020

### ISSUE THREAD

**Issue by EDemerzel** [vivoconference/vivo2020#3]
@awoods would you mind getting this process started for us?

**Comment by awoods** [comment]
I would love to help. Can you be more specific about what this ticket is asking for? Are you asking to have the site published?

**Comment by EDemerzel** [comment]
This would be in reference to both the DNS NAME settings and the publication of the site.  Thanks!

**Comment by awoods** [comment]
What do we want the site URL to be?

**Comment by roflinn** [comment]
https://vivoconference.org/ -> https://vivoconference.org/vivo2020/

**Comment by awoods** [comment]
Done: https://vivoconference.org/ should now redirect to https://vivoconference.org/vivo2020
